### ISSUE TITLE
Please remove Brandi York

### ISSUE THREAD

**Issue by sandman98321** [critdream/critdream-app#1]
Hello,
My wife is Brandi York, she requested removal from your project.  Please remove her.  

I was originally going to fork this to remove her and send you a PR, but realized I don't know enough about the backend on this to be confident that just removing the YAML and the credit from the website are all that needs done.

Trying to not be too critical and hoping you will take feedback:
You're engaging with a community that is HIGHLY sensitive about this stuff.

Engaging with the artists ahead of time would have been...much better.

You're not monetizing it and you are giving attribution.  Yay!

You also did it without asking first.  Dude.  I'd throw a tomato at you if I could.  That was just silly amounts of not reading the room.

What _might_ be more palatable?  Displaying both the original art alongside the generative art derived from it, giving both artist and AI equal time.

**Comment by cosmicBboy** [comment]
Done. I've removed all images based on fine-tuned character art work of critical role-specific character for all the artists.

> You also did it without asking first. Dude. I'd throw a tomato at you if I could. That was just silly amounts of not reading the room.

My original email to Brandi was made in good faith, as an attempt to see if there's any collaboration between AI developers and artists. Based on her and others' feedback, I've scaled down and changed the course of this project.

The emails I've received so far have been high quality, civil, and also been received in good faith. Your language, out of everyone I've talked to in this project so far, has been the most escalatory. A reaction like yours is understandable, but you already communicated what you wanted effectively before this statement, no need to bring mob mentality dynamics into this. Good day.
